### ISSUE TITLE
Add back README.md to the dist version?

### ISSUE THREAD

**Issue by mxr576** [loophp/iterators#59]
README.md contains useful information for new comers, it is a super-slim documentation, so even if I usually prefer excluding documentation from dist versions, for this package ,I would consider having it bundled with the dist version as well. What do you think?

![image](https://github.com/user-attachments/assets/9df23afa-2602-4c22-b83f-f489dc7528ae)

**Comment by drupol** [comment]
mmmh you're making a point but at the same time, I'm balanced between 2 waters. Since the README file is available online, I don't see the point of having it in `vendor/`. I personally never go in `vendor/` for checking the documentation.
If you don't mind, I would prefer to keep the `dist` as small as possible.

**Comment by mxr576** [comment]
It is no problem if you keep the current behavior :) However let me tell you what I did yesterday.

Yes, it is available online therefore I constantly jump between PHPStorm and a web browser tab to see the extra context that is not available in the code. PHPStorm nicely jumped to the class definition (that opened vendor/... instantly in project browser due to my PHPStorm settings) and then I realize, "Hey, if README.md would be here, I could just pin tab in PHPStorm and never look back to my browser.". 

I was also surprised that this was my methodology discovering what is available in this package and what is not.

So maybe this could be a DX improve... maybe I was doing something special.

By the way, thank you for this package! :muscle:

**Comment by drupol** [comment]
You're making a valid point, but I prefer to keep it as it is.

> By the way, thank you for this package! 💪

Thanks! Curious to learn why you're using it!

**Comment by mxr576** [comment]
Atm, I am trying to build (again) a memory and performance efficient lazy list implementation for Drupal 10+ that also holds Drupal dearest changeability information in it, so bubbling up a list of entities and listing specific cacheability information at the call site becomes super simple and easy with this approach. Less magic in upper layers...

The Collection seemed and overkill for this, but these underlying building blocks helped a lot.

**Comment by drupol** [comment]
Interesting!

Yeah `loophp/collection` is huge and not efficient for small amount of items. I should build a more efficient version of it, but then I would avoid making it immutable. Maybe this is something I should do.

**Comment by mxr576** [comment]
Hm, I think you were referring to something else with immutability, but that also reminded me that I may need to build an immutable version of `\Drupal\Core\Cache\CacheableMetadata` (again) to ensure it does not poison my collection.

**Comment by drupol** [comment]
Yeah... but using immutable objects means creating a new instance at each single least modification, I'm not sure if this is a good idea for a caching object.

**Comment by drupol** [comment]
haha enjoy! Writing `loophp/collection` and `loophp/iterators` were the thing I really enjoyed in PHP, hope you'll have fun too in your quest! Drupal needs improvements ;)

**Comment by mxr576** [comment]
Thank you! :grimacing:
