### ISSUE TITLE
FilterIterableAggregate, the $iterable constructor parameter should be generic

### ISSUE THREAD

**Issue by mxr576** [loophp/iterators#60]
## Steps required to reproduce the problem

Just got this report from PHPStan on my generic collection

```
  187    Parameter #2 $predicate of class loophp\iterators\FilterIterableAggregate constructor expects Closure(T, TKey, iterable<TKey, T>): bool, Closure(T, TKey,               
         Foo<TKey, T>): bool given.                                                                                               
         💡 Type Foo<TKey, T> of parameter #3 of passed callable needs to be same or wider than parameter type iterable<TKey, T>  
            of accepting callable.                      
```

This simple change could solve the issue:
![image](https://github.com/user-attachments/assets/f790eac1-3289-4dd5-91da-2c6330c8216f)

What do you think?

## Expected Result

-

## Actual Result

-

**Comment by drupol** [comment]
The template is already defined here: https://github.com/loophp/iterators/blob/a0ba41c111f9c3eb09642ad9260cd6753edeb3e0/src/FilterIterableAggregate.php#L12

**Comment by drupol** [comment]
Mmmh I'm not convinced. Also, I think there's a typo in your snippet.

1. `s/tempalte/template` 
2. Why not adding `template T of iterable` at line 12? Have you tried?

**Comment by mxr576** [comment]
Yes there could a type, line 12 could also work. The actual improvement is making the $iterable parameter generic, anyhow.

**Comment by mxr576** [comment]
My focus was shift a bit, I'll try to come up with an actual fix
